/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgencySerializerMini } from './agencySerializerMini';
import { AstronautStatus } from './astronautStatus';
import { AstronautType } from './astronautType';
import { LaunchSerializerCommon } from './launchSerializerCommon';
import { SpacecraftFlight } from './spacecraftFlight';


export interface AstronautDetailed { 
    readonly id?: number;
    readonly url?: string;
    name: string;
    status?: AstronautStatus;
    type?: AstronautType;
    agency?: AgencySerializerMini;
    dateOfBirth?: string;
    dateOfDeath?: string;
    nationality: string;
    twitter?: string;
    instagram?: string;
    bio: string;
    readonly profileImage?: string;
    readonly profileImageThumbnail?: string;
    wiki?: string;
    readonly flights?: Array<LaunchSerializerCommon>;
    readonly landings?: Array<SpacecraftFlight>;
    readonly lastFlight?: string;
    readonly firstFlight?: string;
}
