/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Landing } from './landing';
import { LaunchSerializerMini } from './launchSerializerMini';
import { LauncherDetailed } from './launcherDetailed';


export interface FirstStage { 
    readonly id?: number;
    readonly type?: string;
    reused?: boolean;
    readonly launcherFlightNumber?: string;
    launcher?: LauncherDetailed;
    landing?: Landing;
    readonly previousFlightDate?: string;
    readonly turnAroundTimeDays?: string;
    previousFlight?: LaunchSerializerMini;
}
