/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgencySerializerMini } from './agencySerializerMini';
import { LaunchStatus } from './launchStatus';
import { Mission } from './mission';
import { Pad } from './pad';
import { Program } from './program';
import { RocketSerializerCommon } from './rocketSerializerCommon';


export interface LaunchSerializerCommon { 
    readonly id?: string;
    readonly url?: string;
    slug: string;
    name?: string;
    status?: LaunchStatus;
    readonly lastUpdated?: Date;
    net?: Date;
    windowEnd?: Date;
    windowStart?: Date;
    probability?: number;
    holdreason?: string;
    failreason?: string;
    hashtag?: string;
    launchServiceProvider?: AgencySerializerMini;
    rocket?: RocketSerializerCommon;
    mission?: Mission;
    pad?: Pad;
    readonly infoURLs?: string;
    readonly vidURLs?: string;
    webcastLive?: boolean;
    readonly image?: string;
    readonly infographic?: string;
    readonly program?: Array<Program>;
}
