/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AgencySerializerDetailedCommon } from './agencySerializerDetailedCommon';
import { InfoURL } from './infoURL';
import { LaunchStatus } from './launchStatus';
import { Mission } from './mission';
import { MissionPatch } from './missionPatch';
import { Pad } from './pad';
import { Program } from './program';
import { RocketDetailed } from './rocketDetailed';
import { Update } from './update';
import { VidURL } from './vidURL';


export interface LaunchDetailed { 
    readonly id?: string;
    readonly url?: string;
    slug: string;
    readonly flightclubUrl?: string;
    readonly rSpacexApiId?: string;
    readonly name?: string;
    status?: LaunchStatus;
    readonly lastUpdated?: Date;
    readonly updates?: Array<Update>;
    readonly net?: Date;
    readonly windowEnd?: Date;
    readonly windowStart?: Date;
    readonly probability?: number;
    readonly holdreason?: string;
    readonly failreason?: string;
    readonly hashtag?: string;
    launchServiceProvider?: AgencySerializerDetailedCommon;
    rocket?: RocketDetailed;
    mission?: Mission;
    pad?: Pad;
    readonly infoURLs?: Array<InfoURL>;
    readonly vidURLs?: Array<VidURL>;
    readonly webcastLive?: boolean;
    readonly image?: string;
    readonly infographic?: string;
    readonly program?: Array<Program>;
    readonly orbitalLaunchAttemptCount?: number;
    readonly locationLaunchAttemptCount?: number;
    readonly padLaunchAttemptCount?: number;
    readonly agencyLaunchAttemptCount?: number;
    readonly orbitalLaunchAttemptCountYear?: number;
    readonly locationLaunchAttemptCountYear?: number;
    readonly padLaunchAttemptCountYear?: number;
    readonly agencyLaunchAttemptCountYear?: number;
    readonly missionPatches?: Array<MissionPatch>;
    notificationsEnabled?: boolean;
}
