/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DockingEventDetailed } from '../model/dockingEventDetailed';
import { InlineResponse20019 } from '../model/inlineResponse20019';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DockingEventService {

    protected basePath = 'https://ll.thespacedevs.com/2.2.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * API endpoint that allows Docking Events to be viewed.
     * @param spaceStationId 
     * @param dockingLocationId 
     * @param flightVehicleId 
     * @param dockingGt 
     * @param dockingLt 
     * @param dockingGte 
     * @param dockingLte 
     * @param search A search term.
     * @param ordering Which field to use when ordering the results.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dockingEventList(spaceStationId?: number, dockingLocationId?: number, flightVehicleId?: number, dockingGt?: string, dockingLt?: string, dockingGte?: string, dockingLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse20019>;
    public dockingEventList(spaceStationId?: number, dockingLocationId?: number, flightVehicleId?: number, dockingGt?: string, dockingLt?: string, dockingGte?: string, dockingLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse20019>>;
    public dockingEventList(spaceStationId?: number, dockingLocationId?: number, flightVehicleId?: number, dockingGt?: string, dockingLt?: string, dockingGte?: string, dockingLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse20019>>;
    public dockingEventList(spaceStationId?: number, dockingLocationId?: number, flightVehicleId?: number, dockingGt?: string, dockingLt?: string, dockingGte?: string, dockingLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {












        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (spaceStationId !== undefined && spaceStationId !== null) {
            queryParameters = queryParameters.set('space_station__id', <any>spaceStationId);
        }
        if (dockingLocationId !== undefined && dockingLocationId !== null) {
            queryParameters = queryParameters.set('docking_location__id', <any>dockingLocationId);
        }
        if (flightVehicleId !== undefined && flightVehicleId !== null) {
            queryParameters = queryParameters.set('flight_vehicle__id', <any>flightVehicleId);
        }
        if (dockingGt !== undefined && dockingGt !== null) {
            queryParameters = queryParameters.set('docking__gt', <any>dockingGt);
        }
        if (dockingLt !== undefined && dockingLt !== null) {
            queryParameters = queryParameters.set('docking__lt', <any>dockingLt);
        }
        if (dockingGte !== undefined && dockingGte !== null) {
            queryParameters = queryParameters.set('docking__gte', <any>dockingGte);
        }
        if (dockingLte !== undefined && dockingLte !== null) {
            queryParameters = queryParameters.set('docking__lte', <any>dockingLte);
        }
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('search', <any>search);
        }
        if (ordering !== undefined && ordering !== null) {
            queryParameters = queryParameters.set('ordering', <any>ordering);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // authentication (Token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Token"]) {
            headers = headers.set('Token', this.configuration.apiKeys["Token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<InlineResponse20019>(`${this.basePath}/docking_event/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * API endpoint that allows Docking Events to be viewed.
     * @param id A unique integer value identifying this docking event.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public dockingEventRead(id: number, observe?: 'body', reportProgress?: boolean): Observable<DockingEventDetailed>;
    public dockingEventRead(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DockingEventDetailed>>;
    public dockingEventRead(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DockingEventDetailed>>;
    public dockingEventRead(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling dockingEventRead.');
        }

        let headers = this.defaultHeaders;

        // authentication (Token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Token"]) {
            headers = headers.set('Token', this.configuration.apiKeys["Token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DockingEventDetailed>(`${this.basePath}/docking_event/${encodeURIComponent(String(id))}/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
