/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - this endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * OpenAPI spec version: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ExpeditionDetail } from '../model/expeditionDetail';
import { InlineResponse20021 } from '../model/inlineResponse20021';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExpeditionService {

    protected basePath = 'https://ll.thespacedevs.com/2.2.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * API endpoint that allows Expeditions to be viewed.
     * @param name 
     * @param crewAstronautAgency 
     * @param spaceStation 
     * @param crewAstronaut 
     * @param startGt 
     * @param startLt 
     * @param startGte 
     * @param startLte 
     * @param endGt 
     * @param endLt 
     * @param endGte 
     * @param endLte 
     * @param search A search term.
     * @param ordering Which field to use when ordering the results.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public expeditionList(name?: string, crewAstronautAgency?: string, spaceStation?: string, crewAstronaut?: string, startGt?: string, startLt?: string, startGte?: string, startLte?: string, endGt?: string, endLt?: string, endGte?: string, endLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse20021>;
    public expeditionList(name?: string, crewAstronautAgency?: string, spaceStation?: string, crewAstronaut?: string, startGt?: string, startLt?: string, startGte?: string, startLte?: string, endGt?: string, endLt?: string, endGte?: string, endLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse20021>>;
    public expeditionList(name?: string, crewAstronautAgency?: string, spaceStation?: string, crewAstronaut?: string, startGt?: string, startLt?: string, startGte?: string, startLte?: string, endGt?: string, endLt?: string, endGte?: string, endLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse20021>>;
    public expeditionList(name?: string, crewAstronautAgency?: string, spaceStation?: string, crewAstronaut?: string, startGt?: string, startLt?: string, startGte?: string, startLte?: string, endGt?: string, endLt?: string, endGte?: string, endLte?: string, search?: string, ordering?: string, limit?: number, offset?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (crewAstronautAgency !== undefined && crewAstronautAgency !== null) {
            queryParameters = queryParameters.set('crew__astronaut__agency', <any>crewAstronautAgency);
        }
        if (spaceStation !== undefined && spaceStation !== null) {
            queryParameters = queryParameters.set('space_station', <any>spaceStation);
        }
        if (crewAstronaut !== undefined && crewAstronaut !== null) {
            queryParameters = queryParameters.set('crew__astronaut', <any>crewAstronaut);
        }
        if (startGt !== undefined && startGt !== null) {
            queryParameters = queryParameters.set('start__gt', <any>startGt);
        }
        if (startLt !== undefined && startLt !== null) {
            queryParameters = queryParameters.set('start__lt', <any>startLt);
        }
        if (startGte !== undefined && startGte !== null) {
            queryParameters = queryParameters.set('start__gte', <any>startGte);
        }
        if (startLte !== undefined && startLte !== null) {
            queryParameters = queryParameters.set('start__lte', <any>startLte);
        }
        if (endGt !== undefined && endGt !== null) {
            queryParameters = queryParameters.set('end__gt', <any>endGt);
        }
        if (endLt !== undefined && endLt !== null) {
            queryParameters = queryParameters.set('end__lt', <any>endLt);
        }
        if (endGte !== undefined && endGte !== null) {
            queryParameters = queryParameters.set('end__gte', <any>endGte);
        }
        if (endLte !== undefined && endLte !== null) {
            queryParameters = queryParameters.set('end__lte', <any>endLte);
        }
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('search', <any>search);
        }
        if (ordering !== undefined && ordering !== null) {
            queryParameters = queryParameters.set('ordering', <any>ordering);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // authentication (Token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Token"]) {
            headers = headers.set('Token', this.configuration.apiKeys["Token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<InlineResponse20021>(`${this.basePath}/expedition/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * API endpoint that allows Expeditions to be viewed.
     * @param id A unique integer value identifying this expedition.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public expeditionRead(id: number, observe?: 'body', reportProgress?: boolean): Observable<ExpeditionDetail>;
    public expeditionRead(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExpeditionDetail>>;
    public expeditionRead(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExpeditionDetail>>;
    public expeditionRead(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling expeditionRead.');
        }

        let headers = this.defaultHeaders;

        // authentication (Token) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Token"]) {
            headers = headers.set('Token', this.configuration.apiKeys["Token"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ExpeditionDetail>(`${this.basePath}/expedition/${encodeURIComponent(String(id))}/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
